### ISSUE TITLE
Digital inverse face

### ISSUE THREAD

**Issue by jhnf** [amazfitbip/watchfaces#1]
[jhn_ru_digital_inverted_v2.zip](https://github.com/amazfitbip/watchfaces/files/1341126/jhn_ru_digital_inverted_v2.zip)

**Comment by dpeddi** [comment]
please can you post with this face installed?

**Comment by jhnf** [comment]
![111](https://user-images.githubusercontent.com/25465808/30979071-32dab55c-a485-11e7-8e53-6659e9016491.jpg)

**Comment by dpeddi** [comment]
face added
